
#pragma once


// 因为要跨几个进程用这些东西，因此尽量不要用枚举。

#define NET_ERRORCODE_BASE      (100)
#define NET_NETWORK_DISCONNECT  (NET_ERRORCODE_BASE + 0)
#define NET_IP_CONFILICT        (NET_ERRORCODE_BASE + 1)
#define NET_SELFCHECK_FAILED    (NET_ERRORCODE_BASE + 2)
#define NET_UNKNOWN_ERROR       (NET_ERRORCODE_BASE + 3)


#define DHCP_ERRORCODE_BASE     (NET_ERRORCODE_BASE + 100)
#define DHCP_XSOCKET_ERROR      (DHCP_ERRORCODE_BASE + 0)
#define DHCP_DISCOVER_TIMEDOUT  (DHCP_ERRORCODE_BASE + 1)
#define DHCP_REQUEST_TIMEDOUT   (DHCP_ERRORCODE_BASE + 2)
#define DHCP_RENEW_TIMEDOUT     (DHCP_ERRORCODE_BASE + 3)
#define DHCP_IP_CONFLICT        (DHCP_ERRORCODE_BASE + 4)


#define PPPOE_ERRORCODE_BASE    (NET_ERRORCODE_BASE + 200)
#define PPPOE_XSOCKER_ERROR     (PPPOE_ERRORCODE_BASE + 0)
#define PPPOE_PADI_TIMEDOUT     (PPPOE_ERRORCODE_BASE + 1)
#define PPPOE_PADR_TIMEDOUT     (PPPOE_ERRORCODE_BASE + 2)
#define PPPOE_AUTH_FAILED       (PPPOE_ERRORCODE_BASE + 3)
#define PPPOE_IPCP_FAILED       (PPPOE_ERRORCODE_BASE + 4)
#define PPPOE_LCP_TIMEDOUT      (PPPOE_ERRORCODE_BASE + 5)


#define WIFI_ERRORCODE_BASE     (NET_ERRORCODE_BASE + 300)
#define WIFI_LOADING_FAILED     (WIFI_ERRORCODE_BASE + 0)
#define WIFI_CONNECT_FAILED     (WIFI_ERRORCODE_BASE + 1)

