#如果sdk的stblinux的linux源码有变化，即制作initrd升级镜像文件所以来的文件会有所变化， 所以需要重新编译最新的linux源码， 然后运行这个脚本， 重新copy最新依赖文件
#如果新的源码新加了其他的模块， 可能会有新的文件需要copy, 所以需要留意。


SRC_DIR=.
DST_DIR=copy_out

if (( $# == 2 )); then 
    SRC_DIR=$1 
    DST_DIR=$2
fi

echo "src: $SRC_DIR dst: $DST_DIR"

__COPY()
{
    if [ ! -e $SRC_DIR/$1 ]; then 
        echo "no such file $SRC_DIR/$1"
        return 
    fi

    if [ -d $SRC_DIR/$1 ]; then
        if [ ! -e $DST_DIR/$1 ]; then 
            mkdir -p $DST_DIR/$1
        fi
        return 
    fi

    echo "cp -f $SRC_DIR/$1  $DST_DIR/$1"
    cp -f $SRC_DIR/$1  $DST_DIR/$1
}

__COPY fs
__COPY fs/built-in.o
__COPY ipc
__COPY ipc/built-in.o
__COPY scripts
__COPY scripts/gen_initramfs_list.sh
__COPY scripts/kallsyms
__COPY arch
__COPY arch/arm
__COPY arch/arm/boot
__COPY arch/arm/boot/compressed
__COPY arch/arm/boot/compressed/piggy.gzip.S
__COPY arch/arm/boot/compressed/vmlinux.lds
__COPY arch/arm/boot/compressed/hyp-stub.o
__COPY arch/arm/boot/compressed/misc.o
__COPY arch/arm/boot/compressed/fdt_rw.o
__COPY arch/arm/boot/compressed/atags_to_fdt.o
__COPY arch/arm/boot/compressed/bswapsdi2.o
__COPY arch/arm/boot/compressed/decompress.o
__COPY arch/arm/boot/compressed/debug.o
__COPY arch/arm/boot/compressed/head.o
__COPY arch/arm/boot/compressed/fdt_ro.o
__COPY arch/arm/boot/compressed/fdt_wip.o
__COPY arch/arm/boot/compressed/lib1funcs.o
__COPY arch/arm/boot/compressed/string.o
__COPY arch/arm/boot/compressed/fdt.o
__COPY arch/arm/boot/compressed/ashldi3.o
__COPY arch/arm/common
__COPY arch/arm/common/built-in.o
__COPY arch/arm/vfp
__COPY arch/arm/vfp/built-in.o
__COPY arch/arm/net
__COPY arch/arm/net/built-in.o
__COPY arch/arm/kernel
__COPY arch/arm/kernel/built-in.o
__COPY arch/arm/kernel/vmlinux.lds
__COPY arch/arm/kernel/head.o
__COPY arch/arm/crypto
__COPY arch/arm/crypto/built-in.o
__COPY arch/arm/lib
__COPY arch/arm/lib/built-in.o
__COPY arch/arm/lib/lib.a
__COPY arch/arm/mm
__COPY arch/arm/mm/built-in.o
__COPY arch/arm/mach-bcm
__COPY arch/arm/mach-bcm/built-in.o
__COPY arch/arm/include
__COPY arch/arm/include/generated
__COPY arch/arm/include/generated/uapi
__COPY arch/arm/include/generated/uapi/asm
__COPY arch/arm/include/generated/asm
__COPY arch/arm/include/generated/asm/bitsperlong.h
__COPY arch/arm/include/uapi
__COPY arch/arm/include/uapi/asm
__COPY arch/arm/include/uapi/asm/statfs.h
__COPY arch/arm/include/uapi/asm/Kbuild
__COPY arch/arm/include/uapi/asm/fcntl.h
__COPY arch/arm/include/uapi/asm/mman.h
__COPY arch/arm/include/uapi/asm/stat.h
__COPY arch/arm/include/uapi/asm/perf_regs.h
__COPY arch/arm/include/uapi/asm/setup.h
__COPY arch/arm/include/uapi/asm/sigcontext.h
__COPY arch/arm/include/uapi/asm/kvm_para.h
__COPY arch/arm/include/uapi/asm/hwcap.h
__COPY arch/arm/include/uapi/asm/ioctls.h
__COPY arch/arm/include/uapi/asm/byteorder.h
__COPY arch/arm/include/uapi/asm/ptrace.h
__COPY arch/arm/include/uapi/asm/kvm.h
__COPY arch/arm/include/uapi/asm/posix_types.h
__COPY arch/arm/include/uapi/asm/unistd.h
__COPY arch/arm/include/uapi/asm/swab.h
__COPY arch/arm/include/uapi/asm/signal.h
__COPY arch/arm/include/asm
__COPY arch/arm/include/asm/types.h
__COPY arch/arm/include/asm/unified.h
__COPY arch/arm/firmware
__COPY arch/arm/firmware/built-in.o
__COPY block
__COPY block/built-in.o
__COPY net
__COPY net/built-in.o
__COPY kernel
__COPY kernel/built-in.o
__COPY crypto
__COPY crypto/built-in.o
__COPY drivers
__COPY drivers/built-in.o
__COPY usr
__COPY usr/gen_init_cpio
__COPY usr/initramfs_data.S
__COPY lib
__COPY lib/built-in.o
__COPY lib/lib.a
__COPY mm
__COPY mm/built-in.o
__COPY include
__COPY include/asm-generic
__COPY include/asm-generic/int-ll64.h
__COPY include/asm-generic/vmlinux.lds.h
__COPY include/generated
__COPY include/generated/compile.h
__COPY include/generated/asm-offsets.h
__COPY include/generated/autoconf.h
__COPY include/generated/utsrelease.h
__COPY include/generated/mach-types.h
__COPY include/generated/bounds.h
__COPY include/generated/uapi
__COPY include/generated/uapi/linux
__COPY include/generated/uapi/linux/version.h
__COPY include/generated/uapi/asm
__COPY include/generated/asm
__COPY include/generated/asm/timex.h
__COPY include/generated/asm/termios.h
__COPY include/generated/asm/ioctl.h
__COPY include/generated/asm/termbits.h
__COPY include/generated/asm/auxvec.h
__COPY include/generated/asm/irq_regs.h
__COPY include/generated/asm/cputime.h
__COPY include/generated/asm/local.h
__COPY include/generated/asm/socket.h
__COPY include/generated/asm/siginfo.h
__COPY include/generated/asm/hash.h
__COPY include/generated/asm/sections.h
__COPY include/generated/asm/exec.h
__COPY include/generated/asm/sembuf.h
__COPY include/generated/asm/segment.h
__COPY include/generated/asm/local64.h
__COPY include/generated/asm/parport.h
__COPY include/generated/asm/shmbuf.h
__COPY include/generated/asm/msgbuf.h
__COPY include/generated/asm/sockios.h
__COPY include/generated/asm/trace_clock.h
__COPY include/generated/asm/param.h
__COPY include/generated/asm/sizes.h
__COPY include/generated/asm/errno.h
__COPY include/generated/asm/poll.h
__COPY include/generated/asm/current.h
__COPY include/generated/asm/preempt.h
__COPY include/generated/asm/kdebug.h
__COPY include/generated/asm/ipcbuf.h
__COPY include/generated/asm/emergency-restart.h
__COPY include/generated/asm/simd.h
__COPY include/generated/asm/serial.h
__COPY include/generated/asm/bitsperlong.h
__COPY include/generated/asm/unaligned.h
__COPY include/generated/asm/resource.h
__COPY include/linux
__COPY include/linux/export.h
__COPY include/linux/kconfig.h
__COPY include/linux/stringify.h
__COPY include/uapi
__COPY include/uapi/drm
__COPY include/uapi/drm/drm_fourcc.h
__COPY include/uapi/drm/i810_drm.h
__COPY include/uapi/drm/Kbuild
__COPY include/uapi/drm/nouveau_drm.h
__COPY include/uapi/drm/sis_drm.h
__COPY include/uapi/drm/radeon_drm.h
__COPY include/uapi/drm/msm_drm.h
__COPY include/uapi/drm/qxl_drm.h
__COPY include/uapi/drm/drm_sarea.h
__COPY include/uapi/drm/omap_drm.h
__COPY include/uapi/drm/drm_mode.h
__COPY include/uapi/drm/r128_drm.h
__COPY include/uapi/drm/via_drm.h
__COPY include/uapi/drm/drm.h
__COPY include/uapi/drm/tegra_drm.h
__COPY include/uapi/drm/savage_drm.h
__COPY include/uapi/drm/mga_drm.h
__COPY include/uapi/drm/i915_drm.h
__COPY include/uapi/drm/armada_drm.h
__COPY include/uapi/drm/exynos_drm.h
__COPY include/uapi/drm/vmwgfx_drm.h
__COPY include/uapi/Kbuild
__COPY include/uapi/rdma
__COPY include/uapi/rdma/ib_user_verbs.h
__COPY include/uapi/rdma/ib_user_mad.h
__COPY include/uapi/rdma/Kbuild
__COPY include/uapi/rdma/ib_user_cm.h
__COPY include/uapi/rdma/rdma_netlink.h
__COPY include/uapi/rdma/rdma_user_cm.h
__COPY include/uapi/rdma/ib_user_sa.h
__COPY include/uapi/xen
__COPY include/uapi/xen/Kbuild
__COPY include/uapi/xen/evtchn.h
__COPY include/uapi/xen/gntalloc.h
__COPY include/uapi/xen/gntdev.h
__COPY include/uapi/xen/privcmd.h
__COPY include/uapi/video
__COPY include/uapi/video/sisfb.h
__COPY include/uapi/video/edid.h
__COPY include/uapi/video/uvesafb.h
__COPY include/uapi/video/Kbuild
__COPY include/uapi/asm-generic
__COPY include/uapi/asm-generic/termios.h
__COPY include/uapi/asm-generic/ioctl.h
__COPY include/uapi/asm-generic/termbits.h
__COPY include/uapi/asm-generic/auxvec.h
__COPY include/uapi/asm-generic/statfs.h
__COPY include/uapi/asm-generic/Kbuild
__COPY include/uapi/asm-generic/fcntl.h
__COPY include/uapi/asm-generic/signal-defs.h
__COPY include/uapi/asm-generic/mman.h
__COPY include/uapi/asm-generic/int-ll64.h
__COPY include/uapi/asm-generic/stat.h
__COPY include/uapi/asm-generic/Kbuild.asm
__COPY include/uapi/asm-generic/socket.h
__COPY include/uapi/asm-generic/siginfo.h
__COPY include/uapi/asm-generic/setup.h
__COPY include/uapi/asm-generic/ucontext.h
__COPY include/uapi/asm-generic/sembuf.h
__COPY include/uapi/asm-generic/types.h
__COPY include/uapi/asm-generic/shmparam.h
__COPY include/uapi/asm-generic/kvm_para.h
__COPY include/uapi/asm-generic/shmbuf.h
__COPY include/uapi/asm-generic/ioctls.h
__COPY include/uapi/asm-generic/msgbuf.h
__COPY include/uapi/asm-generic/sockios.h
__COPY include/uapi/asm-generic/param.h
__COPY include/uapi/asm-generic/errno.h
__COPY include/uapi/asm-generic/poll.h
__COPY include/uapi/asm-generic/posix_types.h
__COPY include/uapi/asm-generic/ipcbuf.h
__COPY include/uapi/asm-generic/unistd.h
__COPY include/uapi/asm-generic/int-l64.h
__COPY include/uapi/asm-generic/swab.h
__COPY include/uapi/asm-generic/mman-common.h
__COPY include/uapi/asm-generic/bitsperlong.h
__COPY include/uapi/asm-generic/errno-base.h
__COPY include/uapi/asm-generic/signal.h
__COPY include/uapi/asm-generic/resource.h
__COPY include/uapi/mtd
__COPY include/uapi/mtd/mtd-user.h
__COPY include/uapi/mtd/Kbuild
__COPY include/uapi/mtd/ubi-user.h
__COPY include/uapi/mtd/inftl-user.h
__COPY include/uapi/mtd/mtd-abi.h
__COPY include/uapi/mtd/nftl-user.h
__COPY include/uapi/scsi
__COPY include/uapi/scsi/Kbuild
__COPY include/uapi/scsi/scsi_bsg_fc.h
__COPY include/uapi/scsi/scsi_netlink_fc.h
__COPY include/uapi/scsi/scsi_netlink.h
__COPY include/uapi/scsi/fc
__COPY include/uapi/scsi/fc/Kbuild
__COPY include/uapi/scsi/fc/fc_els.h
__COPY include/uapi/scsi/fc/fc_fs.h
__COPY include/uapi/scsi/fc/fc_ns.h
__COPY include/uapi/scsi/fc/fc_gs.h
__COPY include/uapi/linux
__COPY include/uapi/linux/timex.h
__COPY include/uapi/linux/termios.h
__COPY include/uapi/linux/ioctl.h
__COPY include/uapi/linux/if_packet.h
__COPY include/uapi/linux/if_arcnet.h
__COPY include/uapi/linux/mdio.h
__COPY include/uapi/linux/loop.h
__COPY include/uapi/linux/in_route.h
__COPY include/uapi/linux/mmc
__COPY include/uapi/linux/mmc/ioctl.h
__COPY include/uapi/linux/mmc/Kbuild
__COPY include/uapi/linux/scc.h
__COPY include/uapi/linux/mii.h
__COPY include/uapi/linux/wireless.h
__COPY include/uapi/linux/gameport.h
__COPY include/uapi/linux/atmioc.h
__COPY include/uapi/linux/netrom.h
__COPY include/uapi/linux/nubus.h
__COPY include/uapi/linux/auxvec.h
__COPY include/uapi/linux/atmsap.h
__COPY include/uapi/linux/sctp.h
__COPY include/uapi/linux/nfs4_mount.h
__COPY include/uapi/linux/joystick.h
__COPY include/uapi/linux/cciss_ioctl.h
__COPY include/uapi/linux/ip6_tunnel.h
__COPY include/uapi/linux/l2tp.h
__COPY include/uapi/linux/affs_hardblocks.h
__COPY include/uapi/linux/Kbuild
__COPY include/uapi/linux/reiserfs_fs.h
__COPY include/uapi/linux/netdevice.h
__COPY include/uapi/linux/vhost.h
__COPY include/uapi/linux/mempolicy.h
__COPY include/uapi/linux/sunrpc
__COPY include/uapi/linux/sunrpc/Kbuild
__COPY include/uapi/linux/sunrpc/debug.h
__COPY include/uapi/linux/netfilter_bridge
__COPY include/uapi/linux/netfilter_bridge/ebt_802_3.h
__COPY include/uapi/linux/netfilter_bridge/ebt_ip6.h
__COPY include/uapi/linux/netfilter_bridge/Kbuild
__COPY include/uapi/linux/netfilter_bridge/ebtables.h
__COPY include/uapi/linux/netfilter_bridge/ebt_log.h
__COPY include/uapi/linux/netfilter_bridge/ebt_redirect.h
__COPY include/uapi/linux/netfilter_bridge/ebt_among.h
__COPY include/uapi/linux/netfilter_bridge/ebt_mark_m.h
__COPY include/uapi/linux/netfilter_bridge/ebt_arpreply.h
__COPY include/uapi/linux/netfilter_bridge/ebt_vlan.h
__COPY include/uapi/linux/netfilter_bridge/ebt_mark_t.h
__COPY include/uapi/linux/netfilter_bridge/ebt_nflog.h
__COPY include/uapi/linux/netfilter_bridge/ebt_pkttype.h
__COPY include/uapi/linux/netfilter_bridge/ebt_nat.h
__COPY include/uapi/linux/netfilter_bridge/ebt_ip.h
__COPY include/uapi/linux/netfilter_bridge/ebt_stp.h
__COPY include/uapi/linux/netfilter_bridge/ebt_arp.h
__COPY include/uapi/linux/netfilter_bridge/ebt_ulog.h
__COPY include/uapi/linux/netfilter_bridge/ebt_limit.h
__COPY include/uapi/linux/fcntl.h
__COPY include/uapi/linux/phonet.h
__COPY include/uapi/linux/neighbour.h
__COPY include/uapi/linux/btrfs.h
__COPY include/uapi/linux/serial_core.h
__COPY include/uapi/linux/netfilter_arp
__COPY include/uapi/linux/netfilter_arp/Kbuild
__COPY include/uapi/linux/netfilter_arp/arp_tables.h
__COPY include/uapi/linux/netfilter_arp/arpt_mangle.h
__COPY include/uapi/linux/kexec.h
__COPY include/uapi/linux/mman.h
__COPY include/uapi/linux/virtio_pci.h
__COPY include/uapi/linux/xfrm.h
__COPY include/uapi/linux/omap3isp.h
__COPY include/uapi/linux/net_dropmon.h
__COPY include/uapi/linux/firewire-constants.h
__COPY include/uapi/linux/i2c.h
__COPY include/uapi/linux/i2c-dev.h
__COPY include/uapi/linux/minix_fs.h
__COPY include/uapi/linux/fadvise.h
__COPY include/uapi/linux/chio.h
__COPY include/uapi/linux/v4l2-dv-timings.h
__COPY include/uapi/linux/gen_stats.h
__COPY include/uapi/linux/netfilter_ipv4
__COPY include/uapi/linux/netfilter_ipv4/ipt_ttl.h
__COPY include/uapi/linux/netfilter_ipv4/Kbuild
__COPY include/uapi/linux/netfilter_ipv4/ipt_ecn.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_ah.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_ULOG.h
__COPY include/uapi/linux/netfilter_ipv4/ip_tables.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_REJECT.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_CLUSTERIP.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_LOG.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_TTL.h
__COPY include/uapi/linux/netfilter_ipv4/ipt_ECN.h
__COPY include/uapi/linux/atmppp.h
__COPY include/uapi/linux/toshiba.h
__COPY include/uapi/linux/stat.h
__COPY include/uapi/linux/cm4000_cs.h
__COPY include/uapi/linux/udp.h
__COPY include/uapi/linux/irqnr.h
__COPY include/uapi/linux/uinput.h
__COPY include/uapi/linux/i2o-dev.h
__COPY include/uapi/linux/uhid.h
__COPY include/uapi/linux/elfcore.h
__COPY include/uapi/linux/major.h
__COPY include/uapi/linux/sonypi.h
__COPY include/uapi/linux/map_to_7segment.h
__COPY include/uapi/linux/udf_fs_i.h
__COPY include/uapi/linux/usbdevice_fs.h
__COPY include/uapi/linux/if_fc.h
__COPY include/uapi/linux/nfs4.h
__COPY include/uapi/linux/sock_diag.h
__COPY include/uapi/linux/meye.h
__COPY include/uapi/linux/virtio_balloon.h
__COPY include/uapi/linux/soundcard.h
__COPY include/uapi/linux/dlm_device.h
__COPY include/uapi/linux/dm-ioctl.h
__COPY include/uapi/linux/som.h
__COPY include/uapi/linux/coda.h
__COPY include/uapi/linux/serial_reg.h
__COPY include/uapi/linux/ipmi.h
__COPY include/uapi/linux/reiserfs_xattr.h
__COPY include/uapi/linux/ncp_fs.h
__COPY include/uapi/linux/usb
__COPY include/uapi/linux/usb/cdc.h
__COPY include/uapi/linux/usb/Kbuild
__COPY include/uapi/linux/usb/gadgetfs.h
__COPY include/uapi/linux/usb/midi.h
__COPY include/uapi/linux/usb/ch9.h
__COPY include/uapi/linux/usb/audio.h
__COPY include/uapi/linux/usb/g_printer.h
__COPY include/uapi/linux/usb/cdc-wdm.h
__COPY include/uapi/linux/usb/tmc.h
__COPY include/uapi/linux/usb/video.h
__COPY include/uapi/linux/usb/ch11.h
__COPY include/uapi/linux/usb/functionfs.h
__COPY include/uapi/linux/dm-log-userspace.h
__COPY include/uapi/linux/selinux_netlink.h
__COPY include/uapi/linux/virtio_ids.h
__COPY include/uapi/linux/atm_eni.h
__COPY include/uapi/linux/mtio.h
__COPY include/uapi/linux/sound.h
__COPY include/uapi/linux/socket.h
__COPY include/uapi/linux/sonet.h
__COPY include/uapi/linux/n_r3964.h
__COPY include/uapi/linux/ax25.h
__COPY include/uapi/linux/ipv6.h
__COPY include/uapi/linux/netconf.h
__COPY include/uapi/linux/elf.h
__COPY include/uapi/linux/bpqether.h
__COPY include/uapi/linux/reboot.h
__COPY include/uapi/linux/hdlcdrv.h
__COPY include/uapi/linux/rds.h
__COPY include/uapi/linux/atmdev.h
__COPY include/uapi/linux/firewire-cdev.h
__COPY include/uapi/linux/jffs2.h
__COPY include/uapi/linux/netlink_diag.h
__COPY include/uapi/linux/pci_regs.h
__COPY include/uapi/linux/tiocl.h
__COPY include/uapi/linux/random.h
__COPY include/uapi/linux/cn_proc.h
__COPY include/uapi/linux/mqueue.h
__COPY include/uapi/linux/qnxtypes.h
__COPY include/uapi/linux/aio_abi.h
__COPY include/uapi/linux/if_slip.h
__COPY include/uapi/linux/kdev_t.h
__COPY include/uapi/linux/hid.h
__COPY include/uapi/linux/raid
__COPY include/uapi/linux/raid/Kbuild
__COPY include/uapi/linux/raid/md_p.h
__COPY include/uapi/linux/raid/md_u.h
__COPY include/uapi/linux/cgroupstats.h
__COPY include/uapi/linux/nfs_mount.h
__COPY include/uapi/linux/kd.h
__COPY include/uapi/linux/netfilter_decnet.h
__COPY include/uapi/linux/if_ltalk.h
__COPY include/uapi/linux/signalfd.h
__COPY include/uapi/linux/dn.h
__COPY include/uapi/linux/nvme.h
__COPY include/uapi/linux/ptp_clock.h
__COPY include/uapi/linux/virtio_config.h
__COPY include/uapi/linux/if_infiniband.h
__COPY include/uapi/linux/blkpg.h
__COPY include/uapi/linux/nfs3.h
__COPY include/uapi/linux/pg.h
__COPY include/uapi/linux/ivtvfb.h
__COPY include/uapi/linux/isdn_ppp.h
__COPY include/uapi/linux/ethtool.h
__COPY include/uapi/linux/audit.h
__COPY include/uapi/linux/i8k.h
__COPY include/uapi/linux/ipv6_route.h
__COPY include/uapi/linux/ultrasound.h
__COPY include/uapi/linux/pktcdvd.h
__COPY include/uapi/linux/if_bonding.h
__COPY include/uapi/linux/ip.h
__COPY include/uapi/linux/vm_sockets.h
__COPY include/uapi/linux/sysctl.h
__COPY include/uapi/linux/nbd.h
__COPY include/uapi/linux/netfilter
__COPY include/uapi/linux/netfilter/xt_LOG.h
__COPY include/uapi/linux/netfilter/xt_comment.h
__COPY include/uapi/linux/netfilter/xt_length.h
__COPY include/uapi/linux/netfilter/xt_RATEEST.h
__COPY include/uapi/linux/netfilter/xt_ipcomp.h
__COPY include/uapi/linux/netfilter/xt_string.h
__COPY include/uapi/linux/netfilter/Kbuild
__COPY include/uapi/linux/netfilter/nfnetlink_compat.h
__COPY include/uapi/linux/netfilter/nf_tables.h
__COPY include/uapi/linux/netfilter/nf_conntrack_sctp.h
__COPY include/uapi/linux/netfilter/xt_tcpmss.h
__COPY include/uapi/linux/netfilter/nfnetlink.h
__COPY include/uapi/linux/netfilter/xt_statistic.h
__COPY include/uapi/linux/netfilter/xt_cgroup.h
__COPY include/uapi/linux/netfilter/xt_devgroup.h
__COPY include/uapi/linux/netfilter/nfnetlink_conntrack.h
__COPY include/uapi/linux/netfilter/xt_MARK.h
__COPY include/uapi/linux/netfilter/xt_NFLOG.h
__COPY include/uapi/linux/netfilter/ipset
__COPY include/uapi/linux/netfilter/ipset/Kbuild
__COPY include/uapi/linux/netfilter/ipset/ip_set_list.h
__COPY include/uapi/linux/netfilter/ipset/ip_set_bitmap.h
__COPY include/uapi/linux/netfilter/ipset/ip_set_hash.h
__COPY include/uapi/linux/netfilter/ipset/ip_set.h
__COPY include/uapi/linux/netfilter/xt_u32.h
__COPY include/uapi/linux/netfilter/xt_CONNMARK.h
__COPY include/uapi/linux/netfilter/nfnetlink_queue.h
__COPY include/uapi/linux/netfilter/nf_conntrack_common.h
__COPY include/uapi/linux/netfilter/xt_cluster.h
__COPY include/uapi/linux/netfilter/xt_pkttype.h
__COPY include/uapi/linux/netfilter/xt_sctp.h
__COPY include/uapi/linux/netfilter/xt_mark.h
__COPY include/uapi/linux/netfilter/xt_helper.h
__COPY include/uapi/linux/netfilter/xt_time.h
__COPY include/uapi/linux/netfilter/xt_limit.h
__COPY include/uapi/linux/netfilter/xt_set.h
__COPY include/uapi/linux/netfilter/nf_conntrack_ftp.h
__COPY include/uapi/linux/netfilter/xt_hashlimit.h
__COPY include/uapi/linux/netfilter/xt_cpu.h
__COPY include/uapi/linux/netfilter/xt_TEE.h
__COPY include/uapi/linux/netfilter/xt_CLASSIFY.h
__COPY include/uapi/linux/netfilter/xt_multiport.h
__COPY include/uapi/linux/netfilter/xt_CT.h
__COPY include/uapi/linux/netfilter/xt_conntrack.h
__COPY include/uapi/linux/netfilter/xt_connlabel.h
__COPY include/uapi/linux/netfilter/xt_TCPOPTSTRIP.h
__COPY include/uapi/linux/netfilter/nfnetlink_acct.h
__COPY include/uapi/linux/netfilter/xt_CHECKSUM.h
__COPY include/uapi/linux/netfilter/xt_DSCP.h
__COPY include/uapi/linux/netfilter/xt_connlimit.h
__COPY include/uapi/linux/netfilter/xt_addrtype.h
__COPY include/uapi/linux/netfilter/xt_mac.h
__COPY include/uapi/linux/netfilter/xt_quota.h
__COPY include/uapi/linux/netfilter/xt_HMARK.h
__COPY include/uapi/linux/netfilter/nf_tables_compat.h
__COPY include/uapi/linux/netfilter/xt_physdev.h
__COPY include/uapi/linux/netfilter/xt_iprange.h
__COPY include/uapi/linux/netfilter/xt_TPROXY.h
__COPY include/uapi/linux/netfilter/xt_esp.h
__COPY include/uapi/linux/netfilter/xt_state.h
__COPY include/uapi/linux/netfilter/xt_TCPMSS.h
__COPY include/uapi/linux/netfilter/xt_nfacct.h
__COPY include/uapi/linux/netfilter/xt_tcpudp.h
__COPY include/uapi/linux/netfilter/xt_l2tp.h
__COPY include/uapi/linux/netfilter/xt_ipvs.h
__COPY include/uapi/linux/netfilter/xt_connbytes.h
__COPY include/uapi/linux/netfilter/nfnetlink_log.h
__COPY include/uapi/linux/netfilter/nf_conntrack_tuple_common.h
__COPY include/uapi/linux/netfilter/xt_NFQUEUE.h
__COPY include/uapi/linux/netfilter/xt_osf.h
__COPY include/uapi/linux/netfilter/xt_policy.h
__COPY include/uapi/linux/netfilter/xt_bpf.h
__COPY include/uapi/linux/netfilter/xt_SYNPROXY.h
__COPY include/uapi/linux/netfilter/xt_dscp.h
__COPY include/uapi/linux/netfilter/nf_nat.h
__COPY include/uapi/linux/netfilter/xt_connmark.h
__COPY include/uapi/linux/netfilter/xt_SECMARK.h
__COPY include/uapi/linux/netfilter/xt_socket.h
__COPY include/uapi/linux/netfilter/xt_dccp.h
__COPY include/uapi/linux/netfilter/nfnetlink_cthelper.h
__COPY include/uapi/linux/netfilter/nfnetlink_cttimeout.h
__COPY include/uapi/linux/netfilter/xt_rateest.h
__COPY include/uapi/linux/netfilter/nf_conntrack_tcp.h
__COPY include/uapi/linux/netfilter/xt_LED.h
__COPY include/uapi/linux/netfilter/xt_AUDIT.h
__COPY include/uapi/linux/netfilter/xt_IDLETIMER.h
__COPY include/uapi/linux/netfilter/xt_owner.h
__COPY include/uapi/linux/netfilter/xt_realm.h
__COPY include/uapi/linux/netfilter/xt_CONNSECMARK.h
__COPY include/uapi/linux/netfilter/xt_ecn.h
__COPY include/uapi/linux/netfilter/xt_recent.h
__COPY include/uapi/linux/netfilter/xt_rpfilter.h
__COPY include/uapi/linux/netfilter/x_tables.h
__COPY include/uapi/linux/nfs2.h
__COPY include/uapi/linux/matroxfb.h
__COPY include/uapi/linux/prctl.h
__COPY include/uapi/linux/shm.h
__COPY include/uapi/linux/const.h
__COPY include/uapi/linux/igmp.h
__COPY include/uapi/linux/snmp.h
__COPY include/uapi/linux/if_frad.h
__COPY include/uapi/linux/hdreg.h
__COPY include/uapi/linux/rtc.h
__COPY include/uapi/linux/hiddev.h
__COPY include/uapi/linux/ip_vs.h
__COPY include/uapi/linux/net_tstamp.h
__COPY include/uapi/linux/b1lli.h
__COPY include/uapi/linux/if_x25.h
__COPY include/uapi/linux/wimax.h
__COPY include/uapi/linux/types.h
__COPY include/uapi/linux/if_alg.h
__COPY include/uapi/linux/fb.h
__COPY include/uapi/linux/packet_diag.h
__COPY include/uapi/linux/genwqe
__COPY include/uapi/linux/genwqe/genwqe_card.h
__COPY include/uapi/linux/watchdog.h
__COPY include/uapi/linux/atm_he.h
__COPY include/uapi/linux/v4l2-subdev.h
__COPY include/uapi/linux/agpgart.h
__COPY include/uapi/linux/atalk.h
__COPY include/uapi/linux/videodev2.h
__COPY include/uapi/linux/futex.h
__COPY include/uapi/linux/cdrom.h
__COPY include/uapi/linux/vt.h
__COPY include/uapi/linux/net.h
__COPY include/uapi/linux/serio.h
__COPY include/uapi/linux/tipc.h
__COPY include/uapi/linux/mroute6.h
__COPY include/uapi/linux/nfs_idmap.h
__COPY include/uapi/linux/pps.h
__COPY include/uapi/linux/virtio_rng.h
__COPY include/uapi/linux/parport.h
__COPY include/uapi/linux/tcp_metrics.h
__COPY include/uapi/linux/vsp1.h
__COPY include/uapi/linux/kvm_para.h
__COPY include/uapi/linux/ppp_defs.h
__COPY include/uapi/linux/ncp.h
__COPY include/uapi/linux/dcbnl.h
__COPY include/uapi/linux/cuda.h
__COPY include/uapi/linux/bfs_fs.h
__COPY include/uapi/linux/kernelcapi.h
__COPY include/uapi/linux/sysinfo.h
__COPY include/uapi/linux/virtio_net.h
__COPY include/uapi/linux/wait.h
__COPY include/uapi/linux/radeonfb.h
__COPY include/uapi/linux/nfc.h
__COPY include/uapi/linux/tcp.h
__COPY include/uapi/linux/perf_event.h
__COPY include/uapi/linux/x25.h
__COPY include/uapi/linux/if_ppp.h
__COPY include/uapi/linux/bcache.h
__COPY include/uapi/linux/patchkey.h
__COPY include/uapi/linux/can
__COPY include/uapi/linux/can/error.h
__COPY include/uapi/linux/can/Kbuild
__COPY include/uapi/linux/can/bcm.h
__COPY include/uapi/linux/can/raw.h
__COPY include/uapi/linux/can/netlink.h
__COPY include/uapi/linux/can/gw.h
__COPY include/uapi/linux/synclink.h
__COPY include/uapi/linux/capi.h
__COPY include/uapi/linux/fd.h
__COPY include/uapi/linux/fuse.h
__COPY include/uapi/linux/iso_fs.h
__COPY include/uapi/linux/media.h
__COPY include/uapi/linux/a.out.h
__COPY include/uapi/linux/raw.h
__COPY include/uapi/linux/fs.h
__COPY include/uapi/linux/romfs_fs.h
__COPY include/uapi/linux/isdn_divertif.h
__COPY include/uapi/linux/mic_ioctl.h
__COPY include/uapi/linux/securebits.h
__COPY include/uapi/linux/rose.h
__COPY include/uapi/linux/ncp_no.h
__COPY include/uapi/linux/capability.h
__COPY include/uapi/linux/v4l2-common.h
__COPY include/uapi/linux/gigaset_dev.h
__COPY include/uapi/linux/isdn.h
__COPY include/uapi/linux/nfsd
__COPY include/uapi/linux/nfsd/Kbuild
__COPY include/uapi/linux/nfsd/export.h
__COPY include/uapi/linux/nfsd/cld.h
__COPY include/uapi/linux/nfsd/debug.h
__COPY include/uapi/linux/nfsd/nfsfh.h
__COPY include/uapi/linux/nfsd/stats.h
__COPY include/uapi/linux/hysdn_if.h
__COPY include/uapi/linux/elf-em.h
__COPY include/uapi/linux/sockios.h
__COPY include/uapi/linux/edd.h
__COPY include/uapi/linux/telephony.h
__COPY include/uapi/linux/coff.h
__COPY include/uapi/linux/string.h
__COPY include/uapi/linux/ipc.h
__COPY include/uapi/linux/atm.h
__COPY include/uapi/linux/baycom.h
__COPY include/uapi/linux/icmpv6.h
__COPY include/uapi/linux/if_bridge.h
__COPY include/uapi/linux/caif
__COPY include/uapi/linux/caif/Kbuild
__COPY include/uapi/linux/caif/caif_socket.h
__COPY include/uapi/linux/caif/if_caif.h
__COPY include/uapi/linux/quota.h
__COPY include/uapi/linux/ivtv.h
__COPY include/uapi/linux/atm_idt77105.h
__COPY include/uapi/linux/limits.h
__COPY include/uapi/linux/falloc.h
__COPY include/uapi/linux/ppp-comp.h
__COPY include/uapi/linux/if_arp.h
__COPY include/uapi/linux/netfilter.h
__COPY include/uapi/linux/rfkill.h
__COPY include/uapi/linux/llc.h
__COPY include/uapi/linux/hdlc.h
__COPY include/uapi/linux/hidraw.h
__COPY include/uapi/linux/ipsec.h
__COPY include/uapi/linux/rtnetlink.h
__COPY include/uapi/linux/if_fddi.h
__COPY include/uapi/linux/cycx_cfm.h
__COPY include/uapi/linux/phantom.h
__COPY include/uapi/linux/irda.h
__COPY include/uapi/linux/ptrace.h
__COPY include/uapi/linux/nvram.h
__COPY include/uapi/linux/adfs_fs.h
__COPY include/uapi/linux/ixjuser.h
__COPY include/uapi/linux/virtio_ring.h
__COPY include/uapi/linux/dlmconstants.h
__COPY include/uapi/linux/pkt_cls.h
__COPY include/uapi/linux/libc-compat.h
__COPY include/uapi/linux/sem.h
__COPY include/uapi/linux/openvswitch.h
__COPY include/uapi/linux/suspend_ioctls.h
__COPY include/uapi/linux/isdnif.h
__COPY include/uapi/linux/v4l2-controls.h
__COPY include/uapi/linux/param.h
__COPY include/uapi/linux/if_team.h
__COPY include/uapi/linux/input.h
__COPY include/uapi/linux/auto_fs.h
__COPY include/uapi/linux/stddef.h
__COPY include/uapi/linux/can.h
__COPY include/uapi/linux/errqueue.h
__COPY include/uapi/linux/connector.h
__COPY include/uapi/linux/inet_diag.h
__COPY include/uapi/linux/hsi
__COPY include/uapi/linux/hsi/Kbuild
__COPY include/uapi/linux/hsi/hsi_char.h
__COPY include/uapi/linux/atmlec.h
__COPY include/uapi/linux/errno.h
__COPY include/uapi/linux/poll.h
__COPY include/uapi/linux/route.h
__COPY include/uapi/linux/sched.h
__COPY include/uapi/linux/fib_rules.h
__COPY include/uapi/linux/cifs
__COPY include/uapi/linux/cifs/cifs_mount.h
__COPY include/uapi/linux/tc_act
__COPY include/uapi/linux/tc_act/Kbuild
__COPY include/uapi/linux/tc_act/tc_mirred.h
__COPY include/uapi/linux/tc_act/tc_pedit.h
__COPY include/uapi/linux/tc_act/tc_nat.h
__COPY include/uapi/linux/tc_act/tc_defact.h
__COPY include/uapi/linux/tc_act/tc_ipt.h
__COPY include/uapi/linux/tc_act/tc_skbedit.h
__COPY include/uapi/linux/tc_act/tc_csum.h
__COPY include/uapi/linux/tc_act/tc_gact.h
__COPY include/uapi/linux/hsr_netlink.h
__COPY include/uapi/linux/kvm.h
__COPY include/uapi/linux/tc_ematch
__COPY include/uapi/linux/tc_ematch/Kbuild
__COPY include/uapi/linux/tc_ematch/tc_em_nbyte.h
__COPY include/uapi/linux/tc_ematch/tc_em_cmp.h
__COPY include/uapi/linux/tc_ematch/tc_em_text.h
__COPY include/uapi/linux/tc_ematch/tc_em_meta.h
__COPY include/uapi/linux/pmu.h
__COPY include/uapi/linux/netlink.h
__COPY include/uapi/linux/if_pppol2tp.h
__COPY include/uapi/linux/veth.h
__COPY include/uapi/linux/nfs_fs.h
__COPY include/uapi/linux/nfsacl.h
__COPY include/uapi/linux/fdreg.h
__COPY include/uapi/linux/if_addrlabel.h
__COPY include/uapi/linux/atmclip.h
__COPY include/uapi/linux/gfs2_ondisk.h
__COPY include/uapi/linux/uvcvideo.h
__COPY include/uapi/linux/keyboard.h
__COPY include/uapi/linux/if_eql.h
__COPY include/uapi/linux/uio.h
__COPY include/uapi/linux/bcm933xx_hcs.h
__COPY include/uapi/linux/bsg.h
__COPY include/uapi/linux/virtio_console.h
__COPY include/uapi/linux/seccomp.h
__COPY include/uapi/linux/blktrace_api.h
__COPY include/uapi/linux/virtio_blk.h
__COPY include/uapi/linux/mic_common.h
__COPY include/uapi/linux/nfs.h
__COPY include/uapi/linux/vfio.h
__COPY include/uapi/linux/times.h
__COPY include/uapi/linux/nl80211.h
__COPY include/uapi/linux/dlm_plock.h
__COPY include/uapi/linux/hash_info.h
__COPY include/uapi/linux/if_hippi.h
__COPY include/uapi/linux/utime.h
__COPY include/uapi/linux/wanrouter.h
__COPY include/uapi/linux/ppdev.h
__COPY include/uapi/linux/dvb
__COPY include/uapi/linux/dvb/osd.h
__COPY include/uapi/linux/dvb/Kbuild
__COPY include/uapi/linux/dvb/ca.h
__COPY include/uapi/linux/dvb/frontend.h
__COPY include/uapi/linux/dvb/net.h
__COPY include/uapi/linux/dvb/dmx.h
__COPY include/uapi/linux/dvb/audio.h
__COPY include/uapi/linux/dvb/version.h
__COPY include/uapi/linux/dvb/video.h
__COPY include/uapi/linux/binfmts.h
__COPY include/uapi/linux/byteorder
__COPY include/uapi/linux/byteorder/Kbuild
__COPY include/uapi/linux/byteorder/big_endian.h
__COPY include/uapi/linux/byteorder/little_endian.h
__COPY include/uapi/linux/ppp-ioctl.h
__COPY include/uapi/linux/qnx4_fs.h
__COPY include/uapi/linux/filter.h
__COPY include/uapi/linux/dqblk_xfs.h
__COPY include/uapi/linux/flat.h
__COPY include/uapi/linux/brcmstb
__COPY include/uapi/linux/brcmstb/cma_driver.h
__COPY include/uapi/linux/omapfb.h
__COPY include/uapi/linux/kernel.h
__COPY include/uapi/linux/msdos_fs.h
__COPY include/uapi/linux/if_vlan.h
__COPY include/uapi/linux/dccp.h
__COPY include/uapi/linux/if_ether.h
__COPY include/uapi/linux/posix_types.h
__COPY include/uapi/linux/hw_breakpoint.h
__COPY include/uapi/linux/fanotify.h
__COPY include/uapi/linux/adb.h
__COPY include/uapi/linux/utsname.h
__COPY include/uapi/linux/mmtimer.h
__COPY include/uapi/linux/time.h
__COPY include/uapi/linux/cyclades.h
__COPY include/uapi/linux/pkt_sched.h
__COPY include/uapi/linux/ipmi_msgdefs.h
__COPY include/uapi/linux/if.h
__COPY include/uapi/linux/if_link.h
__COPY include/uapi/linux/unistd.h
__COPY include/uapi/linux/icmp.h
__COPY include/uapi/linux/unix_diag.h
__COPY include/uapi/linux/personality.h
__COPY include/uapi/linux/kernel-page-flags.h
__COPY include/uapi/linux/if_cablemodem.h
__COPY include/uapi/linux/netfilter_ipv6.h
__COPY include/uapi/linux/elf-fdpic.h
__COPY include/uapi/linux/dlm_netlink.h
__COPY include/uapi/linux/apm_bios.h
__COPY include/uapi/linux/acct.h
__COPY include/uapi/linux/if_addr.h
__COPY include/uapi/linux/virtio_9p.h
__COPY include/uapi/linux/xattr.h
__COPY include/uapi/linux/wimax
__COPY include/uapi/linux/wimax/Kbuild
__COPY include/uapi/linux/wimax/i2400m.h
__COPY include/uapi/linux/netfilter_bridge.h
__COPY include/uapi/linux/swab.h
__COPY include/uapi/linux/atm_tcp.h
__COPY include/uapi/linux/pci.h
__COPY include/uapi/linux/uuid.h
__COPY include/uapi/linux/mei.h
__COPY include/uapi/linux/arcfb.h
__COPY include/uapi/linux/dlm.h
__COPY include/uapi/linux/if_plip.h
__COPY include/uapi/linux/if_tun.h
__COPY include/uapi/linux/netfilter_ipv6
__COPY include/uapi/linux/netfilter_ipv6/ip6t_hl.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_REJECT.h
__COPY include/uapi/linux/netfilter_ipv6/Kbuild
__COPY include/uapi/linux/netfilter_ipv6/ip6t_LOG.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_frag.h
__COPY include/uapi/linux/netfilter_ipv6/ip6_tables.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_ipv6header.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_NPT.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_ah.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_opts.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_mh.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_HL.h
__COPY include/uapi/linux/netfilter_ipv6/ip6t_rt.h
__COPY include/uapi/linux/tty.h
__COPY include/uapi/linux/sdla.h
__COPY include/uapi/linux/netfilter_arp.h
__COPY include/uapi/linux/atmsvc.h
__COPY include/uapi/linux/keyctl.h
__COPY include/uapi/linux/tty_flags.h
__COPY include/uapi/linux/fsl_hypervisor.h
__COPY include/uapi/linux/serial.h
__COPY include/uapi/linux/coda_psdev.h
__COPY include/uapi/linux/tipc_config.h
__COPY include/uapi/linux/atmarp.h
__COPY include/uapi/linux/fiemap.h
__COPY include/uapi/linux/taskstats.h
__COPY include/uapi/linux/atm_zatm.h
__COPY include/uapi/linux/if_pppox.h
__COPY include/uapi/linux/atmapi.h
__COPY include/uapi/linux/atm_nicstar.h
__COPY include/uapi/linux/mroute.h
__COPY include/uapi/linux/cciss_defs.h
__COPY include/uapi/linux/ncp_mount.h
__COPY include/uapi/linux/atmmpc.h
__COPY include/uapi/linux/cramfs_fs.h
__COPY include/uapi/linux/module.h
__COPY include/uapi/linux/v4l2-mediabus.h
__COPY include/uapi/linux/signal.h
__COPY include/uapi/linux/oom.h
__COPY include/uapi/linux/screen_info.h
__COPY include/uapi/linux/zorro_ids.h
__COPY include/uapi/linux/eventpoll.h
__COPY include/uapi/linux/if_tunnel.h
__COPY include/uapi/linux/ipx.h
__COPY include/uapi/linux/efs_fs_sb.h
__COPY include/uapi/linux/isdn
__COPY include/uapi/linux/isdn/Kbuild
__COPY include/uapi/linux/isdn/capicmd.h
__COPY include/uapi/linux/zorro.h
__COPY include/uapi/linux/resource.h
__COPY include/uapi/linux/auto_fs4.h
__COPY include/uapi/linux/netfilter_ipv4.h
__COPY include/uapi/linux/magic.h
__COPY include/uapi/linux/genetlink.h
__COPY include/uapi/linux/hpet.h
__COPY include/uapi/linux/lp.h
__COPY include/uapi/linux/hdlc
__COPY include/uapi/linux/hdlc/ioctl.h
__COPY include/uapi/linux/hdlc/Kbuild
__COPY include/uapi/linux/msg.h
__COPY include/uapi/linux/spi
__COPY include/uapi/linux/spi/Kbuild
__COPY include/uapi/linux/spi/spidev.h
__COPY include/uapi/linux/pfkeyv2.h
__COPY include/uapi/linux/if_phonet.h
__COPY include/uapi/linux/un.h
__COPY include/uapi/linux/in6.h
__COPY include/uapi/linux/in.h
__COPY include/uapi/linux/atmbr2684.h
__COPY include/uapi/linux/inotify.h
__COPY include/uapi/asm
__COPY include/uapi/asm/statfs.h
__COPY include/uapi/asm/Kbuild
__COPY include/uapi/asm/fcntl.h
__COPY include/uapi/asm/mman.h
__COPY include/uapi/asm/stat.h
__COPY include/uapi/asm/perf_regs.h
__COPY include/uapi/asm/setup.h
__COPY include/uapi/asm/sigcontext.h
__COPY include/uapi/asm/kvm_para.h
__COPY include/uapi/asm/hwcap.h
__COPY include/uapi/asm/ioctls.h
__COPY include/uapi/asm/byteorder.h
__COPY include/uapi/asm/ptrace.h
__COPY include/uapi/asm/kvm.h
__COPY include/uapi/asm/posix_types.h
__COPY include/uapi/asm/unistd.h
__COPY include/uapi/asm/swab.h
__COPY include/uapi/asm/signal.h
__COPY include/uapi/sound
__COPY include/uapi/sound/firewire.h
__COPY include/uapi/sound/Kbuild
__COPY include/uapi/sound/hdsp.h
__COPY include/uapi/sound/sfnt_info.h
__COPY include/uapi/sound/emu10k1.h
__COPY include/uapi/sound/asound.h
__COPY include/uapi/sound/sb16_csp.h
__COPY include/uapi/sound/compress_params.h
__COPY include/uapi/sound/asound_fm.h
__COPY include/uapi/sound/hdspm.h
__COPY include/uapi/sound/asequencer.h
__COPY include/uapi/sound/compress_offload.h
__COPY security
__COPY security/built-in.o
__COPY init
__COPY init/built-in.o
__COPY firmware
__COPY firmware/built-in.o
__COPY sound
__COPY sound/built-in.o
